package com.ljy.librarymanager.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ljy.librarymanager.mvp.entity.SearchHistory;
import com.ljy.librarymanager.mvp.entity.User;

import com.ljy.librarymanager.greendao.SearchHistoryDao;
import com.ljy.librarymanager.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
